baseURL = 'https://galadrimteam.github.io/adomin/'
languageCode = 'fr-FR'
title = 'Adomin - Docs'
theme = 'hugo-book'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'
